version: "3.8"
services:
  postgres-products:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-products-data:/var/lib/postgresql/data

  postgres-customers:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-customers-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

volumes:
  postgres-products-data:
  postgres-customers-data:
